export const products = [
  {
    id: 1,
    title: "Cadena",
    price: 5000,
    stock: 5,
    description: "cadena enchapada",
    category: "collares",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657628/samples/aifey/cadena_wuamup.jpg",
  },
  {
    id: 2,
    title: "Collar de Amatista",
    price: 10000,
    stock: 4,
    description: "collar de amatista",
    category: "collares",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657628/samples/aifey/collarAmatista_myprvj.jpg",
  },
  {
    id: 3,
    title: "Chocker",
    price: 6000,
    stock: 2,
    description: "collar chocker negro con piedra",
    category: "collares",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657628/samples/aifey/collarChocker_inekx8.jpg",
  },
  {
    id: 4,
    title: "Collar cruz",
    price: 11000,
    stock: 4,
    description: "collar de palta con dije de cruz",
    category: "collares",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657628/samples/aifey/collarCruz_chqvok.jpg",
  },
  {
    id: 5,
    title: "Collar de Luna",
    price: 13000,
    stock: 7,
    description: "collar enchapado con dije de luna y estrellas",
    category: "collares",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657628/samples/aifey/collarLunaEstrellas_erntlg.jpg",
  },
  {
    id: 6,
    title: "Aritos Piedra",
    price: 6000,
    stock: 4,
    description: "arito abridor de plata con piedra rosa",
    category: "aritos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657717/samples/aifey/aritoPiedrasPlateados_hbxv5q.jpg",
  },
  {
    id: 7,
    title: "Aritos de mariposa",
    price: 8000,
    stock: 8,
    description: "aritos colgantes de mariposa",
    category: "aritos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657717/samples/aifey/aritoMariposaLargos_zum7nc.jpg",
  },
  {
    id: 8,
    title: "Aritos de cruz",
    price: 7000,
    stock: 2,
    description: "aritos de plata con cruz",
    category: "aritos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657716/samples/aifey/aritCruz_evbc2n.jpg",
  },
  {
    id: 9,
    title: "Arito argolla",
    price: 5000,
    stock: 3,
    description: "Argolla plateada",
    category: "aritos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657716/samples/aifey/aritoArgolla_zriwag.jpg",
  },
  {
    id: 10,
    title: "Arito de pluma",
    price: 9000,
    stock: 6,
    description: "aritos artesanales de pluma",
    category: "aritos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657717/samples/aifey/aritoPlumaPluma_dixwdx.jpg",
  },
  {
    id: 11,
    title: "Arito serpiente",
    price: 12000,
    stock: 3,
    description: "aritos colgantes de plata de serpiente",
    category: "aritos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657717/samples/aifey/aritosSerpientesLargos_bmhgkm.jpg",
  },
  {
    id: 12,
    title: "Anillo con cruz",
    price: 10000,
    stock: 5,
    description: "anillo de plata con cruz",
    category: "anillos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657730/samples/aifey/anilloCruz_dgr4w8.jpg",
  },
  {
    id: 13,
    title: "Anillo astas",
    price: 7000,
    stock: 3,
    description: "anillo regulable. modelo astas",
    category: "anillos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657730/samples/aifey/anilloAstas_ezu6qj.jpg",
  },
  {
    id: 14,
    title: "Anillo arbol+corazon",
    price: 12000,
    stock: 8,
    description: "anillo de plata arbol + corazon",
    category: "anillos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657730/samples/aifey/anilloCorazonArbol_ewituf.jpg",
  },
  {
    id: 15,
    title: "anillo strass",
    price: 4000,
    stock: 2,
    description: "anillo con strass y piedras rosas",
    category: "anillos",
    img: "https://res.cloudinary.com/dtkr8ubqa/image/upload/v1688657731/samples/aifey/anilloStrass_xqvxs3.jpg",
  },
];
